"""Local, gitignored persistence for the daily Kite access token.

The access token expires every morning and is regenerated by
``scripts/refresh_token.py``. It is a secret and must never touch git — it lives
under ``secrets/`` (covered by .gitignore) with owner-only permissions.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path

DEFAULT_TOKEN_PATH = Path("secrets/kite_token.json")


@dataclass(frozen=True)
class KiteToken:
    """A persisted Kite session token."""

    access_token: str
    public_token: str | None = None
    user_id: str | None = None
    login_time: str | None = None


class TokenStore:
    """Reads and writes the Kite access token to a local JSON file."""

    def __init__(self, path: Path | str = DEFAULT_TOKEN_PATH) -> None:
        self.path = Path(path)

    def save(self, token: KiteToken) -> None:
        """Persist ``token`` with owner-only (0600) permissions."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        payload = json.dumps(asdict(token), indent=2)
        # Write then tighten permissions so the secret is never world-readable.
        self.path.write_text(payload, encoding="utf-8")
        os.chmod(self.path, 0o600)

    def load(self) -> KiteToken | None:
        """Return the stored token, or ``None`` if no valid file exists."""
        if not self.path.exists():
            return None
        data = json.loads(self.path.read_text(encoding="utf-8"))
        if not data.get("access_token"):
            return None
        return KiteToken(
            access_token=data["access_token"],
            public_token=data.get("public_token"),
            user_id=data.get("user_id"),
            login_time=data.get("login_time"),
        )
